### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [jakesboy2/vimscape2007.nvim#1]
Hi. This looks like a very interesting project with lots of potential! What license applies to it?

**Comment by jakewaldrip** [comment]
Hey! Thanks, apologies as its still early in development (not even ready to be used at the moment, hoping it will be soon). I've added a bit to the readme in the meantime to avoid confusion :) 

 I will likely add an official license at that point, but you can consider it [MIT](https://opensource.org/license/mit).

**Comment by LifeCANvs** [comment]
> Hey! Thanks, apologies as its still early in development (not even ready to be used at the moment, hoping it will be soon). I've added a bit to the readme in the meantime to avoid confusion :)
> 
> I will likely add an official license at that point, but you can consider it [MIT](https://opensource.org/license/mit).

Cool, thanks... and good luck with your journey forward with this - I am definitely keeping a close eye on your project, as it really interests me and I would like to see it evolve into a successful, fun and useful tool for use in software development! When my programming skills progress to a higher level, I would really like to get involved and contribute to this project of yours. It could be quite exciting!

**Comment by jakewaldrip** [comment]
Will be happy to have your help!
